[package]
name = "bouyomi"
version = "0.1.2"
authors = ["Hiromitsu Oshiba <0x75960@strelka.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "0.5"

